### PR TITLE
rate-limiter: fix clock skew if enabling auto-tuned.

### LINKED ISSUE #17995: qps drop to zero when injection one of tikv time lags 5 minutes behind
### What version of TiKV are you using?
master

### What operating system and CPU are you using?
8c/32g

### Steps to reproduce
1、run tpcc
2、injection one of tikv time lags 5 minutes behind

### What did happened?
qps drop to zero when injection one of tikv time lags 5 minutes behind

Image

### PR DESCRIPTION
**Pull request by LykxSassinator**
## Issue
Close https://github.com/tikv/tikv/issues/17995
Currently, in TIKV, there are two issues encountered when enabling auto-tuning on WriteAmpBasedRateLimiter in the presence of clock-skew problems:
- The `Request()` operation may experience excessive waiting if the time offset is too large, causing pending compactions to hang unexpectedly.
- The `Tune()` process uses an excessively small value for updated bytes to calculate the next `rate_bytes_per_sec_`. This results in the next `Request()` being starved, as `rate_bytes_per_sec_` becomes significantly smaller than the pending requested bytes.

image

## Introduction to this PR
To address these two issues in the presence of clock-skew problems, this PR introduces the following changes:
- Clamps the wait-time limit between 0 and `refill_period_us_` to prevent excessively long waits.
- To preserve the current tuning algorithm, the maximum rate limiter is used if it encounters clock-skew issues, ensuring that `Request()` operations do not starve.

After applying this PR, the testing results as followings shows proves that it can solve the clock-skew problem as expected:
image

### CODE REVIEW

**Review by Connor1996 — APPROVED** [review]
LGTM

File: utilities/rate_limiters/write_amp_based_rate_limiter.cc [hunk 1]
```diff
@@ -359,20 +363,33 @@ Status WriteAmpBasedRateLimiter::Tune() {
...
+  // Define the max limit of tick duration limits to handle clock skew.
+  const auto max_tune_tick_duration_limit =
+      std::chrono::microseconds(secs_per_tune_ * 1000 * 1000) * 7 /
+      4;  // 1.75x multiplier
 
   std::chrono::microseconds prev_tuned_time = tuned_time_;
   tuned_time_ = std::chrono::microseconds(NowMicrosMonotonic(env_));
   auto duration = tuned_time_ - prev_tuned_time;
+  // Use max rate limiter if duration is invalid or exceeds max limit:
+  // (1) negative durations indicate clock skew
```
Comment (v01dstar) [inline utilities/rate_limiters/write_amp_based_rate_limiter.cc]: image
Maybe comparing `tuned_time_` and `prev_tuned_time` first, instead of using subtraction .

**Review by glorv — APPROVED** [review]
